// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dynprog_interface
NumericMatrix dynprog_interface(NumericVector data_vec, int max_segments);
RcppExport SEXP _rpackage2_dynprog_interface(SEXP data_vecSEXP, SEXP max_segmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data_vec(data_vecSEXP);
    Rcpp::traits::input_parameter< int >::type max_segments(max_segmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(dynprog_interface(data_vec, max_segments));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rpackage2_dynprog_interface", (DL_FUNC) &_rpackage2_dynprog_interface, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rpackage2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
