# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dynprog_interface <- function(data_vec, max_segments) {
    .Call(`_rpackage2_dynprog_interface`, data_vec, max_segments)
}

